"""Shared paths and helpers for the Farmer's Delight -> CraftEngine pack generator."""
import json
import os
import re
import shutil
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
MOD_SRC = REPO / "src" / "main"
MOD_ASSETS = MOD_SRC / "resources" / "assets" / "farmersdelight"
MOD_DATA = MOD_SRC / "resources" / "data"
MOD_JAVA = MOD_SRC / "java" / "com" / "nhoryzon" / "mc" / "farmersdelight"

PLUGIN = REPO / "papo-plugin"
CE_PACK = PLUGIN / "src" / "main" / "resources" / "ce-pack"
CE_RP = CE_PACK / "resourcepack" / "assets" / "farmersdelight"
PLUGIN_RECIPES = PLUGIN / "src" / "main" / "resources" / "recipes"

NS = "farmersdelight"


def clean_output():
    if CE_PACK.exists():
        shutil.rmtree(CE_PACK)
    (CE_PACK / "configuration").mkdir(parents=True)
    (CE_RP / "textures").mkdir(parents=True)
    (CE_RP / "models").mkdir(parents=True)
    (CE_RP / "sounds").mkdir(parents=True)
    if PLUGIN_RECIPES.exists():
        shutil.rmtree(PLUGIN_RECIPES)
    PLUGIN_RECIPES.mkdir(parents=True)


def load_json(path: Path):
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


def yaml_str(s: str) -> str:
    """Quote a string for YAML emission."""
    return '"' + str(s).replace('\\', '\\\\').replace('"', '\\"') + '"'


def dump_yaml_section(root_key: str, body: str) -> str:
    return f"{root_key}:\n{body}"


def write_config(name: str, sections: list[tuple[str, str]]):
    """Write one configuration file made of multiple root sections (uses `#` section ids
    when the same root key appears more than once)."""
    seen: dict[str, int] = {}
    parts = [f"# Generated by tools/ce_gen — Farmer's Delight mod -> CraftEngine pack\n"]
    for root, body in sections:
        if not body.strip():
            continue
        count = seen.get(root, 0)
        seen[root] = count + 1
        key = root if count == 0 else f"{root}#{count}"
        parts.append(f"{key}:\n{body}")
    out = CE_PACK / "configuration" / name
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(parts), encoding="utf-8")
    return out


def rel_texture(tex: str) -> str:
    """farmersdelight:block/x -> farmersdelight:block/x (already relative ref)."""
    return tex


def iter_blockstates():
    for f in sorted((MOD_ASSETS / "blockstates").glob("*.json")):
        yield f.stem, load_json(f)


def block_model_exists(model: str) -> bool:
    if model.startswith("minecraft:"):
        return True
    p = model.split(":", 1)[1] if ":" in model else model
    return (MOD_ASSETS / "models" / (p + ".json")).exists()


def read_java(path: Path) -> str:
    return path.read_text(encoding="utf-8")
